all:	makall

makall: iflop/iflop.com mbrol/mbrol.com
	sync

clean:
	(cd iflop; make clean)
	(cd mbrol; make clean)
	
iflop/iflop.com:
	(cd iflop; make)

mbrol/mbrol.com:
	(cd mbrol; make)


	

